import {
  AirVent,
  Archive,
  Armchair,
  BadgeCheck,
  BatteryCharging,
  Bike,
  Box,
  Boxes,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  CardSim,
  Cctv,
  Cloud,
  Cog,
  Computer,
  ContactRound,
  CreditCard,
  FileBadge,
  FileSignature,
  FireExtinguisher,
  Footprints,
  Forklift,
  Fuel,
  Gauge,
  Globe,
  Hammer,
  Hand,
  HardHat,
  Headphones,
  House,
  IdCard,
  Keyboard,
  KeyRound,
  Landmark,
  Laptop,
  type LucideIcon,
  Microwave,
  Monitor,
  Mouse,
  Package,
  PencilRuler,
  PlugZap,
  Printer,
  Projector,
  Repeat,
  Router,
  ScanLine,
  Server,
  ShieldCheck,
  Smartphone,
  Sofa,
  Table,
  Tablet,
  Truck,
  Tv,
  Wrench,
  Zap,
} from 'lucide-react';
import { cn } from './utils';

/** Icons an admin can pick for categories and asset types. */
export const ICONS: Record<string, LucideIcon> = {
  box: Box,
  package: Package,
  laptop: Laptop,
  computer: Computer,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  server: Server,
  printer: Printer,
  router: Router,
  keyboard: Keyboard,
  mouse: Mouse,
  'plug-zap': PlugZap,
  headphones: Headphones,
  'battery-charging': BatteryCharging,
  'card-sim': CardSim,
  briefcase: Briefcase,
  armchair: Armchair,
  table: Table,
  archive: Archive,
  'key-round': KeyRound,
  'id-card': IdCard,
  'contact-round': ContactRound,
  'pencil-ruler': PencilRuler,
  car: Car,
  bike: Bike,
  bus: Bus,
  truck: Truck,
  forklift: Forklift,
  wrench: Wrench,
  cog: Cog,
  hammer: Hammer,
  gauge: Gauge,
  zap: Zap,
  'hard-hat': HardHat,
  footprints: Footprints,
  hand: Hand,
  'fire-extinguisher': FireExtinguisher,
  'shield-check': ShieldCheck,
  camera: Camera,
  projector: Projector,
  tv: Tv,
  'scan-line': ScanLine,
  'credit-card': CreditCard,
  'badge-check': BadgeCheck,
  repeat: Repeat,
  globe: Globe,
  cloud: Cloud,
  'file-badge': FileBadge,
  'building-2': Building2,
  'air-vent': AirVent,
  fuel: Fuel,
  sofa: Sofa,
  cctv: Cctv,
  microwave: Microwave,
  landmark: Landmark,
  house: House,
  'file-signature': FileSignature,
  boxes: Boxes,
};

export const ICON_NAMES = Object.keys(ICONS);

/** Tailwind classes per category colour. */
export const COLORS: Record<string, { bg: string; text: string; bar: string }> = {
  blue: { bg: 'bg-blue-100 dark:bg-blue-950/60', text: 'text-blue-700 dark:text-blue-300', bar: 'bg-blue-500' },
  indigo: { bg: 'bg-indigo-100 dark:bg-indigo-950/60', text: 'text-indigo-700 dark:text-indigo-300', bar: 'bg-indigo-500' },
  violet: { bg: 'bg-violet-100 dark:bg-violet-950/60', text: 'text-violet-700 dark:text-violet-300', bar: 'bg-violet-500' },
  emerald: { bg: 'bg-emerald-100 dark:bg-emerald-950/60', text: 'text-emerald-700 dark:text-emerald-300', bar: 'bg-emerald-500' },
  amber: { bg: 'bg-amber-100 dark:bg-amber-950/60', text: 'text-amber-700 dark:text-amber-300', bar: 'bg-amber-500' },
  orange: { bg: 'bg-orange-100 dark:bg-orange-950/60', text: 'text-orange-700 dark:text-orange-300', bar: 'bg-orange-500' },
  red: { bg: 'bg-red-100 dark:bg-red-950/60', text: 'text-red-700 dark:text-red-300', bar: 'bg-red-500' },
  cyan: { bg: 'bg-cyan-100 dark:bg-cyan-950/60', text: 'text-cyan-700 dark:text-cyan-300', bar: 'bg-cyan-500' },
  slate: { bg: 'bg-slate-200 dark:bg-slate-800', text: 'text-slate-700 dark:text-slate-300', bar: 'bg-slate-500' },
  stone: { bg: 'bg-stone-200 dark:bg-stone-800', text: 'text-stone-700 dark:text-stone-300', bar: 'bg-stone-500' },
  rose: { bg: 'bg-rose-100 dark:bg-rose-950/60', text: 'text-rose-700 dark:text-rose-300', bar: 'bg-rose-500' },
  teal: { bg: 'bg-teal-100 dark:bg-teal-950/60', text: 'text-teal-700 dark:text-teal-300', bar: 'bg-teal-500' },
};
export const COLOR_NAMES = Object.keys(COLORS);

export function DynamicIcon({ name, className }: { name: string | null | undefined; className?: string }) {
  const Icon = (name && ICONS[name]) || Box;
  return <Icon className={className} />;
}

/** Rounded tile with the category colour and the type / category icon. */
export function AssetIcon({ icon, color, className, size = 'md' }: { icon: string | null | undefined; color: string | null | undefined; className?: string; size?: 'sm' | 'md' | 'lg' }) {
  const c = COLORS[color ?? ''] ?? COLORS.slate;
  const dims = { sm: 'size-7 rounded-md [&_svg]:size-3.5', md: 'size-9 rounded-lg [&_svg]:size-4.5', lg: 'size-12 rounded-xl [&_svg]:size-6' }[size];
  return (
    <span className={cn('inline-flex shrink-0 items-center justify-center', dims, c.bg, c.text, className)}>
      <DynamicIcon name={icon} />
    </span>
  );
}
