# Generated by Django 6.1.1 on 2026-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklistitem',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
