# Generated by Django 6.1.1 on 2026-09-19 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_taskchecklistitem_due_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('did', models.TextField(max_length=2000)),
                ('plan_tomorrow', models.TextField(blank=True, default='', max_length=2000)),
                ('percent_done', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minutes_spent', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_day_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to='crm.task')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['task', 'date'], name='crm_taskday_task_id_79494b_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'date'), name='uniq_task_day_log')],
            },
        ),
    ]
