# Generated by Django 6.1 on 2026-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales'), ('purchase_manager', 'Purchase Manager'), ('purchase', 'Purchase Team'), ('accounts_manager', 'Accounts Manager'), ('accounts', 'Accounts'), ('it_lead', 'IT Lead'), ('it_team', 'IT Team'), ('developer_manager', 'Developer Manager'), ('developer', 'Developer'), ('warehouse_manager', 'Warehouse Manager'), ('warehouse', 'Warehouse Team'), ('rider', 'Rider'), ('housekeeping', 'Housekeeping'), ('security', 'Security'), ('legal', 'Legal'), ('hr_executive', 'HR Executive'), ('hr_manager', 'HR Manager')], default='sales_executive', max_length=20),
        ),
    ]
