# Generated by Django 6.1.2 on 2026-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_works_week_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_person_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
